//==========================================================================
// File Name   : DVRIMA.inc
// Description : SACM DVRIMA API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __DVRIMA_INC__
.define __DVRIMA_INC__

.external F_SACM_DVRIMA_Initial
.external F_SACM_DVRIMA_Rec
.external F_SACM_DVRIMA_Play
.external F_SACM_DVRIMA_Stop
.external F_SACM_DVRIMA_Volume
.external F_SACM_DVRIMA_Pause
.external F_SACM_DVRIMA_Resume
.external F_SACM_DVRIMA_Status
.external F_SACM_DVRIMA_ServiceLoop
.external F_ISR_Service_SACM_DVRIMA

.endif
//========================================================================================        
// End of SACM_DVRIMA.inc
//========================================================================================